### ISSUE TITLE
"URI lookup on X failed" when UTF-8 sequence present in identifier

### ISSUE THREAD

**Issue by GregIthaca** [ge-high-assurance/RACK#320] opened 2021-03-12 14:06 UTC
We found a few odd instances of data ingestion that failed where all the other rows of data worked fine.  The culprit seemed to be identifiers which contained UTF-8 sequences representing Unicode symbols/punctuation.  They ingest successfully in the originating dataset, but then they fail the "ErrorIfMissing" test when trying to cross reference them.

An example might be a word like "Geo\xe2\x88\x92location" where the hyphen was for some reason replaced by U+2212 in the source document.

Obviously this can be solved by filtering them out at the source, but I thought you'd want to know about the discrepancy between ingestion and query.

**Comment by cuddihyge** [comment] 2021-04-01 13:37
I am unable to reproduce this bug as described. 

This junit adds an identifier containing the UTF-8 hyphen, then does a URILookup and adds a description:
```com.ge.research.semtk.load.test.DataLoaderTest_IT.test_LookupBatteryIdAddDescUTF8()```

Is it possible that you are trying to put the UTF-8 character in the URI itself?   And then look it up?
I do see a potential bug there.   Since UTF-8 characters are not valid in URI's, SemTK replaces it with an underscore.
If you tried to do a lookup on that URI without replacing the UTF-8 with an underscore, then that would fail.

Please note this:
-  applies to looking up the actual URI containing UTF-8 (potential bug), 
- does **not** affect looking up an object that has an identifier string that contains UTF-8

If this is indeed the problem, I could engineer a solution.   But it may cause backwards-compatibility risks, and is generally not a very good practice to begin with.

**Please send a full example** with the nodegroups and data, so I can understand further.  @GregIthaca

**Comment by cuddihyge** [comment] 2021-04-02 13:13
@russell-d-e  has provided a test case.   

This issue is not a simple UTF-8 problem.    We have observed these unusual features
- some URI lookups with UTF-8 work fine (e.g. the junit test) while others fail.
- our test case currently passes in @cuddihyge 's dev environment but fails in Docker 5.1

@tuxji  :  do you have any idea where we even start to figure out why it would fail in Docker but not eclipse?    Java version?  Fuseki version?

I will continue to investigate.

**Comment by kquick** [comment] 2021-04-02 15:46
This may be due to a LOCALE setting; container images often do not have LOCALE set by default and need them to be explicitly set.

**Comment by cuddihyge** [comment] 2021-04-02 18:20
Confirmed that it is NOT a fuseki version difference.   The test passes in my dev environment with both Fuseki 3.10 and 3.16.

Confirmed that it is not the LANG environment variable.   The test still fails in docker when I start with:
```docker run -e LANG --detach -p 80:80 -p 12050-12092:12050-12092 gehighassurance/rack-box:v5.1```

**Comment by cuddihyge** [comment] 2021-04-02 18:22
I can not find a LOCALE env variable set in docker nor my dev environment.

**Comment by cuddihyge** [comment] 2021-04-02 18:31
[ingest_REQUIREMENTS.zip](https://github.com/ge-high-assurance/RACK/files/6250832/ingest_REQUIREMENTS.zip)

Here are the two files which cause the failure when ingested against ingest_REQUIREMENTS.json.

...in case anyone else is feeling adventurous.

**Comment by cuddihyge** [comment] 2021-04-05 14:53
I have confirmed that this bug only happens inside the **docker image**. 
@tuxji  and I spent some time trying to change LOCALE and other environment variables inside docker to figure this out.

I hope @tuxji or someone with more docker expertise can take over the lead on this issue.  I'm running low on ideas.

**Comment by tuxji** [comment] 2021-04-26 17:08
I’ve done everything I can do to ensure that the Docker container has an “en_US.UTF-8” locale defined, but the URI lookup still fails on the UTF-8 character in Docker.  I think we may have been chasing a red herring; maybe there’s something else about Docker that’s causing the URI lookup to fail.  

Here’s what I did to ensure that the Docker image has a locale defined.  I modified the packer install script to install the locales-all package, which has pre-compiled data files for all the major locales, and changed the packer build template to define the LANG environment variable in the container's metadata.  

I confirmed that when I open a CLI inside the Docker container and type “locale -a” or “locale”, I see that all the locales are installed and the default locale is set to en_US.UTF-8.  All child processes running inside the Docker container should have inherited the LANG environment variable, but to make doubly certain of it, I edited the fuseki.service and /home/ubuntu/semtk-opensource/environment files to make sure they defined LANG=en_US.UTF-8 and restarted all the Java processes.  I even edited /etc/init.d/nginx to make sure it defined and exported LANG=en_US.UTF-8 and restarted the nginx service too.  The Docker container still gets the URI lookup failure, however, so the problem must go deeper than just not having a locale defined.

**Comment by cuddihyge** [comment] 2021-04-26 21:16
I think we shouldn't invest more time into this for now.   Thanks for all your help, John.

**Comment by AbhaMoitra** [comment] 2021-06-24 20:40
UTF-8 checks present in CLI, so closing this.

**Closed by AbhaMoitra** 2021-06-24 20:40 UTC
Labels: SemTK, TA1, bug

**Comment by GregIthaca** [comment] 2023-10-26 20:04
Just a passing note, that we are still seeing this in v12 with new datasets generated from different documents. We have an identifier `2 7 3 8 OCTET-STRING` where the hyphen is not ASCII 0x2d but rather Latin-1 0xad, and while it has no problem ingesting the identifier when the REQUIREMENT1.csv file is processed, it can't find it when the AcertRequirementModel2.csv file tries to look up and existing entry using the `models_identifier` field.

The error is `...,URI lookup on [?THING] failed on: 2 7 3 8 OCTET?STRING,...`
