### ISSUE TITLE
SemTK - sub-properties spanning namespaces cause SPARQL generation error

### ISSUE THREAD

**Issue by Robert-Adelard** [ge-high-assurance/RACK#530] opened 2021-07-30 10:00 UTC
I am using `dispatchSelectByIdSync` to run nodegroup queries - however, I have suddenly started getting unexpected 500 errors for certain nodegroups.

According to my Web Proxy, the request I'm sending is:
```
{
	"nodeGroupId": "query HLR without software test",
	"sparqlConnection": "NODEGROUP_DEFAULT",
	"runtimeConstraints": null
}
```
and the response from the Nodegroup Execution Service is
```
{
	"message": "operations failed.",
	"rationale": "nodeGroupExecutionService/dispatchSelectByIdSync threw java.lang.Exception Query failed: Query failed: Error 400: Bad Request\n\ncom.ge.research.semtk.services.nodeGroupExecution.NodeGroupExecutionRestController.dispatchSelectByIdSync(NodeGroupExecutionRestController.java:683)\njdk.internal.reflect.GeneratedMethodAccessor187.invoke(Unknown Source)\njava.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n...",
	"status": "failure"
}
```
Given that other nodegroups are working fine, I suspect I may have triggered a bug in SemTK by editing and saving this nodegroup under a different name.

**Comment by cuddihyge** [comment] 2021-07-30 12:26
Please attach a copy of the nodegroup JSON to this issue.  (Nodegroup->download)

**Comment by cuddihyge** [comment] 2021-07-30 12:29
While the query is loaded into SPARQLgraph, could you paste the SPARQL (from the middle panel) into this issue also.  Thx.

**Comment by Robert-Adelard** [comment] 2021-07-30 12:30
The nodegroups affected are unremarkable and execute without error from SPARQL Graph, although that uses a different REST API.

On reflection, I think I may have hit some kind of limit - I have created 20-30 nodegroups recently and at some point this morning the Nodegroup Execution Service started to refuse to run the new nodegroups, although it is quite happy to run the old nodegroups.

**Comment by Robert-Adelard** [comment] 2021-07-30 12:34
Here is the query generated by SPARQLgraph

```
prefix rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix DevelopmentPlan:<http://Turnstile/DevelopmentPlan#>
prefix PROV_S:<http://arcos.rack/PROV-S#>
prefix rdfs:<http://www.w3.org/2000/01/rdf-schema#>
prefix XMLSchema:<http://www.w3.org/2001/XMLSchema#>
prefix generated:<http://semtk.research.ge.com/generated#>
select distinct ?Description ?High_Level_Requirement
		FROM <http://rack001/data>
		FROM <http://rack001/do-178c>
		FROM <http://rack001/model>
 where {
	?HighLevelRequirement a DevelopmentPlan:HighLevelRequirement .
	?HighLevelRequirement PROV_S:description ?description .
	BIND(?description as ?Description) .
	?HighLevelRequirement PROV_S:identifier ?identifier_0 .
	BIND(?identifier_0 as ?High_Level_Requirement) .
	minus {
		?SoftwareComponentTest (PROV_S:wasDerivedFrom|PROV_S:wasImpactedBy|http://arcos.rack/TESTING#verifies|PROV_S:wasRevisionOf) ?HighLevelRequirement .
			?SoftwareComponentTest a DevelopmentPlan:SoftwareComponentTest .
	}
}
```

**Comment by cuddihyge** [comment] 2021-07-30 12:34
In that case, send one of the JSON files, and let me know exactly what steps you used to load it into the store.

**Comment by Robert-Adelard** [comment] 2021-07-30 12:35
I created the nodegroups in SPARQLgraph and saved them in the node store - as I said, I've done this 20-30 times in the last couple of days without problems, so I think I've hit some kind of limit.

**Comment by Robert-Adelard** [comment] 2021-07-30 12:37
We've checked the logs on the RACK server, and there's nothing strange apart from the Java exception - would you like to see the full stack trace?

**Comment by Robert-Adelard** [comment] 2021-07-30 12:39
Here's the JSON file for one of the queries...

```
{
	"version": 3,
	"sparqlConn": {
		"name": "RACK local fuseki",
		"domain": "",
		"enableOwlImports": false,
		"model": [
			{
				"type": "fuseki",
				"url": "http://localhost:3030/RACK",
				"graph": "http://rack001/model"
			}
		],
		"data": [
			{
				"type": "fuseki",
				"url": "http://localhost:3030/RACK",
				"graph": "http://rack001/data"
			},
			{
				"type": "fuseki",
				"url": "http://localhost:3030/RACK",
				"graph": "http://rack001/do-178c"
			}
		]
	},
	"sNodeGroup": {
		"version": 13,
		"limit": 0,
		"offset": 0,
		"sNodeList": [
			{
				"propList": [
					{
						"ValueType": "string",
						"relationship": "http://www.w3.org/2001/XMLSchema#string",
						"UriRelationship": "http://arcos.rack/PROV-S#description",
						"Constraints": "",
						"SparqlID": "?description",
						"isReturned": false,
						"optMinus": 0,
						"isRuntimeConstrained": false,
						"instanceValues": [],
						"isMarkedForDeletion": false,
						"binding": "?Description",
						"isBindingReturned": true
					},
					{
						"ValueType": "string",
						"relationship": "http://www.w3.org/2001/XMLSchema#string",
						"UriRelationship": "http://arcos.rack/PROV-S#identifier",
						"Constraints": "",
						"SparqlID": "?identifier_0",
						"isReturned": false,
						"optMinus": 0,
						"isRuntimeConstrained": false,
						"instanceValues": [],
						"isMarkedForDeletion": false,
						"binding": "?High_Level_Requirement",
						"isBindingReturned": true
					}
				],
				"nodeList": [],
				"fullURIName": "http://Turnstile/DevelopmentPlan#HighLevelRequirement",
				"SparqlID": "?HighLevelRequirement",
				"isReturned": false,
				"isRuntimeConstrained": false,
				"valueConstraint": "",
				"instanceValue": null,
				"deletionMode": "NO_DELETE"
			},
			{
				"propList": [],
				"nodeList": [
					{
						"SnodeSparqlIDs": [
							"?HighLevelRequirement"
						],
						"OptionalMinus": [
							-2
						],
						"Qualifiers": [
							""
						],
						"DeletionMarkers": [
							false
						],
						"ValueType": "ENTITY",
						"UriValueType": "http://arcos.rack/PROV-S#ENTITY",
						"ConnectBy": "wasDerivedFrom",
						"Connected": true,
						"UriConnectBy": "http://arcos.rack/PROV-S#wasDerivedFrom"
					}
				],
				"fullURIName": "http://Turnstile/DevelopmentPlan#SoftwareComponentTest",
				"SparqlID": "?SoftwareComponentTest",
				"isReturned": false,
				"isRuntimeConstrained": false,
				"valueConstraint": "",
				"instanceValue": null,
				"deletionMode": "NO_DELETE"
			}
		],
		"orderBy": [],
		"unionHash": {}
	},
	"importSpec": {
		"version": "1",
		"baseURI": "",
		"columns": [],
		"dataValidator": [],
		"texts": [],
		"transforms": [],
		"nodes": [
			{
				"sparqlID": "?SoftwareComponentTest",
				"type": "http://Turnstile/DevelopmentPlan#SoftwareComponentTest",
				"mapping": [],
				"props": []
			},
			{
				"sparqlID": "?HighLevelRequirement",
				"type": "http://Turnstile/DevelopmentPlan#HighLevelRequirement",
				"mapping": [],
				"props": []
			}
		]
	},
	"plotSpecs": []
}
```

**Comment by Robert-Adelard** [comment] 2021-07-30 12:40
Sorry - GitHub won't let me attach the file.

**Comment by cuddihyge** [comment] 2021-07-30 12:51
I'm not sure what environment you're in, but if you can use the RACK cli tool, could you do this from a bash script:

1. mkdir ISSUE530
2. rack nodegroups export [a-z] ISSUE530
3. zip up the ISSUE530 folder and email it to cuddihy@ge.com
4. give me the names of one working and one non-working nodegroup

In case you haven't set up the RACK cli, the instructions are on the wiki here: [RACK-CLI](https://github.com/ge-high-assurance/RACK/wiki/RACK-CLI)


In addition:  If you can see/find the fuseki log, it is more likely to have some useful information.     (We seem to be getting a 400 from Fuseki)

**Comment by Robert-Adelard** [comment] 2021-07-30 13:08
Aha - I found this in the Fuseki log:

```
[2021-07-30 12:30:56] Fuseki     INFO  [39441] 400 Parse error: 
prefix rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix DevelopmentPlan:<http://Turnstile/DevelopmentPlan#>
prefix PROV_S:<http://arcos.rack/PROV-S#>
prefix rdfs:<http://www.w3.org/2000/01/rdf-schema#>
prefix XMLSchema:<http://www.w3.org/2001/XMLSchema#>
prefix generated:<http://semtk.research.ge.com/generated#>
select distinct ?Description ?High_Level_Requirement
		FROM <http://rack001/data>
		FROM <http://rack001/do-178c>
		FROM <http://rack001/model>
 where {
	?HighLevelRequirement a DevelopmentPlan:HighLevelRequirement .
	?HighLevelRequirement PROV_S:description ?description .
	BIND(?description as ?Description) .
	?HighLevelRequirement PROV_S:identifier ?identifier_0 .
	BIND(?identifier_0 as ?High_Level_Requirement) .
	minus {
		?SoftwareComponentTest (PROV_S:wasDerivedFrom|PROV_S:wasImpactedBy|http://arcos.rack/TESTING#verifies|PROV_S:wasRevisionOf) ?HighLevelRequirement .
			?SoftwareComponentTest a DevelopmentPlan:SoftwareComponentTest .
	}
}


Line 18, column 84: Unresolved prefixed name: http: (2 ms)
```

**Comment by Robert-Adelard** [comment] 2021-07-30 13:09
For some reason, there isn't a TESTING prefix.

**Comment by cuddihyge** [comment] 2021-07-30 13:45
OK.  Thanks for helping reproduce this.  I am able to reproduce it enough that I can investigate.

I can't get your exact error,  the nodegroup you sent works in ```dispatchSelectByIdSync``` and in SPARQLgraph, but I can see the error in the SPARQL generated into the middle pane.  This ought to be enough to allow me to track it down.

Summary and better title:
**Sub-properties that span namespaces result in incorrect SPARQL (missing prefix, syntax error on unprefixed predicate)**

I'll try to figure out:

- why the SPARQL is wrong in SPARQLgraph (i.e. hit **Run** on the SPARQL pane fails)
- why sending the nodegroup from SPARQLgraph seems to result in **correct** SPARQL
- why retrieving the nodegroup from the store results in **inconsistent** SPARQL

**Comment by Robert-Adelard** [comment] 2021-07-30 13:51
Thanks - I'm glad to hear you've been able to reproduce the problem. Can you suggest a workaround / quick fix? Or is it best to avoid queries that span namespaces for now?

**Comment by Robert-Adelard** [comment] 2021-07-30 14:01
A partial explanation of the second point above, namely

- why sending the nodegroup from SPARQLgraph  seems to result in **correct** SPARQL, 

might be that SPARQLgraph is using `dispatchSelectFromNodegroup` and sending a `jsonRenderedNodegroup` rather than a nodegroup ID.

Perhaps something is going wrong with the conversion from a `jsonRenderedNodegroup` to SPARQL.

**Comment by Robert-Adelard** [comment] 2021-07-30 14:55
Can you confirm whether the JSON representations of the nodegroup queries is correct?

**Comment by cuddihyge** [comment] 2021-07-30 14:59
I believe the nodegroups are correct (so they will work once the issue is resolved).

I don't have a work-around at this time.

The issue is not so broad as an entire query that spans namespaces.  It appears to be specifically predicates that have subProperties that span namespaces.

**Comment by cuddihyge** [comment] 2021-07-30 18:45
I've coded up a fix for this issue and it will be in the -dev RACK docker image later today.  

@Robert-Adelard please try it out monday or later and confirm your problem is fixed.

**Comment by Robert-Adelard** [comment] 2021-08-02 11:42
Thank you for the quick fix - I can confirm that this seems to have addressed the problem.

**Closed** 2021-08-02 15:06 UTC
Labels: SemTK, bug
